### ISSUE TITLE
Empecher lancement de deux fois le même workflow en meme temps / Pouvoir stop le process en court

### ISSUE THREAD

**Issue by alex3144** [assemblee-virtuelle/Semantic-Bus#134]

**Comment by simonLouvet** [comment]
done, le engine ne traitera as le component suivant si le process est stoppé. Cela n’empêche pas un composant de tourner à l'infini et de consommer des ressources. Le fait de stopper ne produit pas d'intéraction immédiate, il faut rafraichir la page pour pouvoir relancer
