### ISSUE TITLE
Visualisation automatique du résultat du workflow problématique

### ISSUE THREAD

**Issue by seballot** [assemblee-virtuelle/Semantic-Bus#135]
Depuis peu lorsque le workflow est calculé, on est automatiquement redirigé vers la page "Consulter".

Personnellement je suis pas trop fan de cette navigation forcée, je ne comprends pas trop l'intérêt car il y a déjà les composants qui changent de couleurs (et ça c'est super!!!)

Egalement deux cas que j'ai rencontré problématiques :
1. Lorsque le worflow est lancé via quelqu'un d'autre, ou via une utilisation de l'api get en fin de worflow etc..., et bien la navigation change également, alors que je ne suis peut être meme pas à l'origine de ce lancement
2. Si je suis en train de créer un composant, et que cette navigation forcée apparait, et bien je perd mes changements

Bisous, merci pour tout le travail !

**Comment by alex3144** [comment]
Bonjour, on va enlever cette redirection dans la prochaine release

**Comment by simonLouvet** [comment]
corrigé
