### ISSUE TITLE
Erreur au lancement

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/Semantic-Bus#253]
Quand j'essaie de lancer avec `make start` j'ai cette erreur:

```
ERROR: for main  Cannot start service main: driver failed programming external connectivity on endpoint main (9eb1f77997603cec193f1fa3be3d0f6157a0913c93cc1eb6ab365ca02cac8f62): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

![image](https://user-images.githubusercontent.com/2728945/176209633-0a152d6f-48af-4348-a007-9dfca004805f.png)

Note: j'ai du modifier select.sh pour ajouter un `sudo` devant la commande `docker-compose` sinon il ne trouvait pas le démon docker
Note: j'ai effectivement déjà un serveur (Apache) qui tourne en local sur ma machine.
Note: je suis sur Ubuntu

**Comment by simonLouvet** [comment]
@thomas, docker-compose ne peut pas lancer le main car il demande l'ouverture du port 80 et qu'il est déjà ouvert pour le serveur apache. tu essaie de le lancer sur un serveur locale ou un serveur de prod? La configuration du docker-compose fourni est pour du locale. Je peux te fournir des docker-compose taillé pour la production si tu veux. Tu peux également modifier les port d'ouverture/redirection entre les docker et la machine physique sur le fichier docker-compose pour éviter le conflit.

**Comment by simonLouvet** [comment]
si tu as du mettre sudo, c'est que ton docker est mal configuré : ton user n'est pas utilisateur docker.
`sudo usermod -aG docker $USER`

**Comment by simonLouvet** [comment]
@tfrancart je peux fermer?

**Comment by tfrancart** [comment]
oui
