### ISSUE TITLE
install info

### ISSUE THREAD

**Issue by corbane** [assemblee-virtuelle/Semantic-Bus#26]
Salut a vous (c Jean-marie du mmfest)!

Je ne sais pas bien utiliser Github et le README ne m’est pas clair. (Je n’arrive pas à l’utiliser en local) 
« ssh-keygen -t rsa ajouter la clef publique généré (.ssh/id_rsa.pub) dans l'admin de github git clone git@github.com:assemblee-virtuelle/Semantic-Bus.git git submodule init git submodule update sudo apt-get install g++ build-essential curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash redemarer console mvn install 8.1.4 nmp install »
C’est une longue phrase pas claire pour moi…:/ Surtout « ssh-keygen -t rsa ajouter la clef publique généré (.ssh/id_rsa.pub) dans l'admin de github » là je ne sais pas où il faut mettre la clef…

(Peut-être connais-tu déjà https://nodered.org/ ?)
merci!

**Comment by corbane** [comment]
Mon msg d'erreur es celui-ci:

git clone git@github.com:assemblee-virtuelle/Semantic-Bus.git
Cloning into 'Semantic-Bus'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).

Mais ça ne m'aide pas beaucoup plus...

**Comment by simonLouvet** [comment]
On a remis à jour le readme (merci 1000i100).
Il semble que tu n'ai pas paramétré ton github (settings->SSH)
Tu peux aussi cloner en HTTPS (sans générer de clef ssh) si tu ne comptes pas contribuer régulièrement. 
Tu peux aussi utiliser le produit en ligne directement : https://semantic-bus.org/ihm/application.html.
Nous avons des soucis de connection sur chrome donc préférez firefox svp.
