### ISSUE TITLE
Unicity component to improve

### ISSUE THREAD

**Issue by Mikoteko** [assemblee-virtuelle/Semantic-Bus#300]
We need to remove the "Champ source" property, the data will be taken from the field "data" instead.
![image](https://user-images.githubusercontent.com/63355855/213145353-950e36c9-8f1b-41c5-92f7-40c7ff56211a.png)

We want to be able to make the unicty not only on objects but on string lists too.

**Comment by simonLouvet** [comment]
Done 07/03/2023
