### ISSUE TITLE
message d'erreur si fond inssufisant

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/Semantic-Bus#31]
L'utilisateur n'est plus averti lorsque ses fonds sont insuffisants pour executer un flow. il doit être averti dans l'interface et les API

**Comment by grizio** [comment]
En regardant le fonctionnement, je remarque deux comportements distincts :

- Il n'y a pas de message d'erreur affiché ou retourné (mais loggé en console)
- Tant que les crédits ne sont pas négatifs, le flow va être exécuté, puis crédité ensuite et non l'inverse

Le deuxième scénario est un bug ou un comportement voulu ?

Dans le premier cas, quel est le bug à corrigé dans ce ticket ?
