### ISSUE TITLE
rabbitmq The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by happy-dev** [assemblee-virtuelle/Semantic-Bus#339]
I get the following error when installing from scratch on MacOS Ventura 13.2 on a M2 chip

```log

 ! rabbitmq The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Comment by simonLouvet** [comment]
salut @happy-dev. 
Je suis bien embeté mais ca fait longtemps qu'on a pas testé d'installer sur un mac.
Le probleme c'est qu'on a plus developeur qui travaille sur mac ...
Est ce que tu as essayé de demarrer en selectionnant linux plutot que mac? les évoltions de mac et docker permet pet être de démarer en linux maintenant.

Si ca ne fonctionne pas et que tu as vraiment besoin de faire demarrer le bus sur un mac, on verra si on peut mettre du temps pour t'aider.

J'espere que tu pourra tester et repondre à ton besoin.

**Comment by happy-dev** [comment]
Salut Simon,

Merci pour ta réponse
Ignore pour le moment tant qu'on n'a pas le financement j'en aurais pas besoin

Pour l'heure stand by de mon côté
Je sais pas s'il faut conserver l'issue ouverte, je te laisse jauger

J'en profite pour te souhaiter heureux et en pleine forme !
Au plaisir de nous revoir

**Comment by simonLouvet** [comment]
Ca va bien même si la vie d'entrepreneur n'est pas de tout repos.
Je ferme l'issue mais n'hésites pas à en ouvrire si besoin ou nous contacter directement.
