### ISSUE TITLE
Supprimer un workflow ne fonctionne pas

### ISSUE THREAD

**Issue by seballot** [assemblee-virtuelle/Semantic-Bus#35]
J'ai bien la pop up "vous êtes sur de supprimer" qui s'affiche, mais quand lick ok rien ne se passe. Si j'actualise la page les worflow sont toujours là

Chromium 70.0

**Comment by Jacx12** [comment]
Cela fonctionne correctement sur IE et Firefox
Il est préférable d'utiliser Firefox pour cette version encore "beta"

**Comment by simonLouvet** [comment]
non reproduit sur les dernières versions
