### ISSUE TITLE
Avoir un nom et une icone pour chaque composant

### ISSUE THREAD

**Issue by seballot** [assemblee-virtuelle/Semantic-Bus#42]
Yop, je pense pas que ça soit beaucoup de taf alors je me permet de demander cette amélioration de l'ergonomie !
Y'a plusieurs composant qui apparaissent comme ça :
![image](https://user-images.githubusercontent.com/17404254/49227260-fbf68700-f3e8-11e8-8b5a-b9e0fc5ea4ef.png)
Un nom (en francais si possible) aiderait grandement les nouveaux utilisateurs je pense !

**Comment by BenFer** [comment]
C’est un simple SVG qui a été conçu pour être modifié facilement

**Comment by Jacx12** [comment]
La v0.3 est en ligne avec les nouveaux visuels.

**Comment by seballot** [comment]
Cool !
