### ISSUE TITLE
Corriger la fonction rechercher un workflow partagé

### ISSUE THREAD

**Issue by Jacx12** [assemblee-virtuelle/Semantic-Bus#47]
Améliorer la fonction de rechercher un Workflow et corriger la fonction rechercher un Workflow partagé

**Comment by grizio** [comment]
J'ai corrigé la fonction de recherche. Par contre, comment veux-tu améliorer la fonction rechercher ?

Elle se base actuellement sur le nom en tant que regex. Comment devrait-elle se comporter ?

**Comment by Jacx12** [comment]
Merci grizio ! 
Actuellement, il y a des comportements étranges avec les résultats de recherche dans Workflow. 
Exemple : il y a 3 Worklows qui commencent par la lettre "C" (Ci, Cr, Co) quand je tape "C" dans la barre, il m'affiche 2 résultats (Cr et Co, et pas le Ci). 
Si ma deuxième lettre est un "i" dans ce cas il m'affiche bien mon Workflow Ci..

J'avais rencontré un autre problème dans le même genre, mais je n'arrive pas à le reproduire. 
Exemple : il y a deux Workflows : "test" et "nouveau test" quand j'entrais "test" dans la barre, il m'affichait le Workflow "nouveau test" et pas le "test".. 
Peut être est ce corrigé depuis.

**Comment by Jacx12** [comment]
Je viens de rajouter deux nouveaux Workflows qui commencent par un Co et un autre Cu pour tester. 
Il me trouve Cr, Cu et un Co sur les deux. Il ne m'affiche pas le Ci.
Je sais pas si je suis claire dans mes exemples, en soit c'est pas une priorité car on retrouve toujours notre résultat. Mais ça m'a bloqué quand je fessais des tests avec plein de Workflow avec des noms similaires.
