### ISSUE TITLE
Transformeur SPARQL

### ISSUE THREAD

**Issue by jmvanel** [assemblee-virtuelle/Semantic-Bus#8]
Composant intermédiaire qui lit et sort du JSON-LD, et permet de faire une requête SPARQL

Triage: autres possibilités de liaison avec le Web Sémantique
- connecteur en entrée SPARQL ( SELECT ou CONSTRUCT)
- connecteur  en sortie SPARQL: on utilise la spec. du W3C pour charger des triplets ( en JSON-LD dans ce cas ) : https://www.w3.org/TR/sparql11-http-rdf-update/

Clairement un plus gros morceau:
- stockage SPARQL à la place ou en + du stockage MongoDB

Lien vers issue Semantic_forms ETL (possibilité de chercher une propriété par son libellé, et son libellé sera en fait le nom de colonne CSV) 
https://github.com/jmvanel/semantic_forms/issues/159

**Comment by simonLouvet** [comment]
Le bus fonctionne en objet pour ne pas être enfermé dans le sémantique tout en permettant d'en faire. Il sera epossible de produire du json+ld (c'est déjà le cas) ou un fichier xml/rdf. possibilité aussi de consommer du rdf/xml ou du json+ld (2 déjà implémenté). Le tout avec des requettes sparql sur le flux d'objet (à condition qu'il ai été sémantisé en json-ld ou que la source soit sémantique).
