### ISSUE TITLE
workspace name update not Working

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/Semantic-Bus#9]
La mise à jour du nom du workspace ne fonctionne pas

**Comment by alex3144** [comment]
Très bien je regarderai

Envoyé de mon iPhone

Le 3 juil. 2017 à 21:00, simonLouvet <notifications@github.com<mailto:notifications@github.com>> a écrit :


La mise à jour du nom du workspace ne fonctionne pas
